# Generated by Django 5.2 on 2026-09-13 06:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('hard', 'Hard Skill'), ('soft', 'Soft Skill')], default='full-time', max_length=20)),
                ('thumbnail', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
