# Generated by Django 5.2 on 2026-09-16 15:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tech_stack', models.CharField(max_length=255)),
                ('project_url', models.URLField(blank=True)),
                ('project_image_url', models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('hard', 'Hard Skill'), ('soft', 'Soft Skill')], default='hard', max_length=20),
        ),
    ]
